export const stateActionTypes = {
  SET_MODAL: "SET_MODAL",
  SET_ACCOUNT: "SET_ACCOUNT",
  SET_CHAINID: "SET_CHAINID",
  SET_WALLET_PROVIDER: "SET_WALLET_PROVIDER",
  SET_ACCOUNT_NFTS: "SET_ACCOUNT_NFTS",
  SET_ACTIVE_TOKEN: "SET_ACTIVE_TOKEN",
  SET_PREVIEW_COLLECTION: "SET_PREVIEW_COLLECTION",
  SET_IPFS_DATA: "SET_IPFS_DATA",
  SET_MINTDATA: "SET_MINTDATA",
  SET_NOTIFICATION: "SET_NOTIFICATION",
  SET_LOADING_SCREEN: "SET_LOADING_SCREEN",
  SET_CREATE_SUCCESS_MODAL: "SET_CREATE_SUCCESS_MODAL",
  SET_MAINNET: "SET_MAINNET",
  SET_ACTIVE_UTILITY_PARAMS: "SET_ACTIVE_UTILITY_PARAMS",
};

export const modalTypes = {
  CONNECT_WALLET: "CONNECT_WALLET",
  SWITCH_NETWORKS: "SWITCH_NETWORKS",
  FEEDBACK: "FEEDBACK",
};
